### ISSUE TITLE
Security/login page is not disabled on first boot when using -Djenkins.install.runSetupWizard=false

### ISSUE THREAD

**Issue by NorseGaud** [jenkinsci/docker#1093]
Related to https://github.com/jenkinsci/docker/pull/833

### Version report

Jenkins and plugins versions report:

Console unavailable; stuck on Sign in page.  Version is `2.277.1`

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
❯ sw_vers
ProductName:    macOS
ProductVersion: 11.2.3
BuildVersion:   20D91
```

Docker Desktop: 3.2.2 (61853)

### Reproduction steps

```
version: '3.7'
services:
  $JENKINS_DOCKER_CONTAINER_NAME:
    container_name: $JENKINS_DOCKER_CONTAINER_NAME
    image: jenkins/jenkins:lts
    restart: always
    ports:
      - "8090:$SERVICE_PORT"
      - "50000:50000"
    volumes:
      - $JENKINS_DATA_DIR:/var/jenkins_home
    environment:
      - JAVA_OPTS="-Djava.util.logging.config.file=/var/jenkins_home/log.properties -Djenkins.install.runSetupWizard=false"
```

Then load the UI and it'll show `Unlock Jenkins`.

I tried https://www.jenkins.io/doc/book/system-administration/security/#disabling-security too and it's just adding back the sections I removed from the config.xml on reboot.

**Comment by oleg-nenashev** [comment]
Likely it is related to https://issues.jenkins.io/browse/JENKINS-65149

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/jenkins/pull/5283 for the related patch

**Comment by oleg-nenashev** [comment]
FTR a fresh install with `docker run -p 8080:8080 --rm -e JAVA_OPTS="-Djenkins.install.runSetupWizard=false" jenkins/jenkins:2.277.1` skips the setup Wizard correctly. I assume it happens only in the case when JENKINS_HOME was initialized before Jenkins 2.4 or Jenkins LTS 2.7.1. Could you please confirm it @NorseGaud ?

**Comment by NorseGaud** [comment]
Here is what I use:
```
version: '3.7'
services:
  anka.jenkins:
    container_name: anka.jenkins
    image: jenkins/jenkins:2.277.1
    restart: always
    ports:
      - "8092:8080"
      - "50000:50000"
    volumes:
      - /Users/nathanpierce/anka.jenkins-data:/var/jenkins_home
    environment:
      # - JENKINS_OPTS=" --httpPort=-1 --httpsPort=8080 "
      - JAVA_OPTS="-Djava.util.logging.config.file=/var/jenkins_home/log.properties -Djenkins.install.runSetupWizard=false"
```

I delete the data directory before each start too.

Am I understanding that the `Unlock Jenkins` screen is part of the setup wizard?
