### ISSUE TITLE
loggin  missing  servier port 

### ISSUE THREAD

**Issue by 3792274** [jenkinsci/docker#1508]
The port is lost after you change the port for login using https

![1](https://user-images.githubusercontent.com/19231863/200228908-034a7139-b8a4-496d-88cd-d82e9f42bc06.png)

---------------------------------------------------------------------------------------------------------------------------------------

![2](https://user-images.githubusercontent.com/19231863/200228916-459964f7-c1c1-49eb-bcf3-e3d437ba386d.png)

-------------------------------------------------------------------------------------------------------------------------------------

 ```yml
version: '2'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    privileged: true
    user: root
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:rw
      - /opt/jenkins/jenkins_home:/var/jenkins_home:rw
      - /opt/nginx/conf/cert/jenkin.pfx:/opt/nginx/conf/cert/jenkin.pfx
    ports:
      - "7070:8080"
      - "444:444"
      - "50000:50000"
    ulimits:
      nproc: 65535
    hostname: jenkins
    mem_limit: 1024m
    restart: always
    environment:
      JAVA_OPTS: -Djava.util.logging.config.file=/var/jenkins_home/log.properties -Duser.timezone=Asia/Shanghai "
      TZ: Asia/Shanghai
      JENKINS_PORT: 444
      JENKINS_OPTS: --httpPort=8080 --httpsPort=444 --httpsRedirectHttp --httpsKeyStore=/opt/nginx/conf/cert/jenkin.pfx --httpsKeyStorePassword=123456
```
