### ISSUE TITLE
Unable to update container to :lts via watchtower

### ISSUE THREAD

**Issue by nitobuendia** [jenkinsci/docker#1557]
### Jenkins and plugins versions report

Jenkins: 2.375.2
OS: Linux 5.15.0-56-generic

### What Operating System are you using (both controller, and any agents involved in the problem)?

Docker running on Ubuntu

### Reproduction steps

Set up Jenkins via docker-compose:

```yaml
version: "3.7"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    environment:
      - TZ=Asia/Singapore
      - JAVA_OPTS=-Duser.timezone=Asia/Sigapore
      - JENKINS_HTTP_PORT=8080
      - JENKINS_HTTPS_PORT=8443
      - JENKINS_HTTPS_KEYSTORE=/var/lib/ssl/privkey.pfx
      - JENKINS_HTTPS_KEYSTORE_PASSWORD=""
      - JENKINS_OPTS=--httpPort=8080 --httpsPort=8443 --httpsKeyStore="/var/lib/ssl/privkey.pfx"
      - PLUGINS_FORCE_UPGRADE=true
      - TRY_UPGRADE_IF_NO_MARKER=true
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./home:/var/jenkins_home
      - ./ssl:/var/lib/ssl
```

Set up watchtower via docker-compose:

```yaml
version: "3"

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    env_file:
      - ./common.env
    environment:
      - WATCHTOWER_SCHEDULE=0 0 3 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./run:/run
```

### Expected Results

Container should update whenever new :lts releases happen.

### Actual Results

```
Could not do a head request for "jenkins/jenkins:lts", falling back to regular pull.
Reason: registry responded to head request with "404 Not Found", auth: "not present"
```

### Anything else?

This did not happen before. The first occurence started on Jan 28th. It seems related to [these changes](https://github.com/containrrr/watchtower/discussions/1529#discussioncomment-4748053). For example, pihole had the same error but they fixed it. The issue also contains links to instructions on how to solve it.
