### ISSUE TITLE
Docker Compose syntax

### ISSUE THREAD

**Issue by cloudlady911** [jenkinsci/docker#201]
I want to use docker compose to pass the required settings for running jenkins on port 443.

I have the certificate and key in one file called cert_and_key.pk12

How exactly would I write the docker compose to pass this information and settings?

**Comment by dweomer** [comment]
I went through https://wiki.jenkins-ci.org/display/JENKINS/Starting+and+Accessing+Jenkins a few times and ended up using a keystore, but something like:

```
  master:
    container_name: jenkins-master
    environment:
      - "JAVA_OPTS=-Djava.awt.headless=true -Duser.timezone=America/Phoenix"
      - "JENKINS_OPTS=--httpPort=-1 --httpsPort=8443 --httpsCertificate=/var/jenkins_home/cert_and_key.pk12 --httpsPrivateKey=/var/jenkins_home/cert_and_key.pk12"
```
