### ISSUE TITLE
JENKINS_VERSION doesn't fetch the right war version

### ISSUE THREAD

**Issue by herau** [jenkinsci/docker#266]
I'm using the `2.0-alpine` jenkins docker image in a docker-compose file but the `JENKINS_VERSION` environment variable doesn't have any effect on the war version in the jenkins image.

With this example below, i want to use the 2.2 version of the war but i the image work with the 2.0 version (fallback value in the dockerfile)
```yml
# docker-compose config
networks: {}
services:
  server:
    environment:
      JENKINS_VERSION: '2.2'
    image: jenkins:2.0-alpine
    ports:
    - 5001:5000
    - 8081:8080
    restart:
      MaximumRetryCount: 0
      Name: always
    user: root
    volumes:
    - /home/data/docker/containers/jenkins/data:/var/jenkins_home:rw
version: '2.0'
volumes: {}
```

is there any issue of using `ARG` and `ENV` in your dockerfile which make the env variable not modifiable ?
