### ISSUE TITLE
compose2 and lack of JDK list

### ISSUE THREAD

**Issue by aleksandra-tarkowska** [jenkinsci/docker#300]
I tried starting up Jenkins image 1.651.1 or 1.651.3 using docker-compose 2

```
version: '2'
services:

    jenkins:
        image: jenkins:1.651.3
        user: ${USER_ID}
        volumes:
            - ./home:/var/jenkins_home
```

this cause lack of JDK list

<img width="1036" alt="firefoxscreensnapz004" src="https://cloud.githubusercontent.com/assets/1065155/16515460/0d518f1c-3f6a-11e6-9b33-cf76172ac240.png">

I never had problems with compose 1
