### ISSUE TITLE
Avoid manual entry of http_proxy

### ISSUE THREAD

**Issue by alexellis** [jenkinsci/docker#302]
What is the best way to start up a jenkins:2.0 instance in a Docker container without having to manually enter the http proxy through a UI?

I have tried using environmental variables in a docker-compose file with no avail.

```
version: '2'
services:
  ci:
    image: jenkins:2.0
    ports:
     - "8080:8080"
     - "50000:50000"
    environment:
     - http_proxy="http://x:y" 
     - https_proxy="http://x:y"
```

Thanks
