### ISSUE TITLE
install-plugins.sh fails with an error when dowloading

### ISSUE THREAD

**Issue by jmMeessen** [jenkinsci/docker#337]
Hello @carlossg 

Ref #335 : I misunderstood some of the indications on Github. I learned something more. Sorry for the noise.

I tried again to rebuild my image with the `jenkinsci/jenkins:latest` and now I get a fatal error in the install-plugins at the first download. At first sight, there is something wrong with a curl parameter. See attached log.
The rebuild was done with `docker-compose build --no-cache --pull jenkins`.

Did I miss something obvious again ?

Jmm

```
Status: Downloaded newer image for jenkinsci/jenkins:latest
 ---> b89d8932ea9c
Step 2 : RUN /usr/local/bin/install-plugins.sh github-oauth workflow-aggregator
 ---> Running in 5856fec550bf
Creating initial locks...

Analyzing war...

Downloading plugins...
Downloading plugin: github-oauth from -https://updates.jenkins.io/download/plugins/github-oauth/latest/github-oauth.hpi
Downloading plugin: workflow-aggregator from -https://updates.jenkins.io/download/plugins/workflow-aggregator/latest/workflow-aggregator.hpi
Usage: curl [options...] <url>
Options: (H) means HTTP/HTTPS only, (F) means FTP only
     --anyauth       Pick "any" authentication method (H)
[ ... removed curl help display  ... ]
Downloaded file is not a valid ZIP: /usr/share/jenkins/ref/plugins/github-oauth.jpi
Downloaded file is not a valid ZIP: /usr/share/jenkins/ref/plugins/workflow-aggregator.jpi

WAR bundled plugins:


Installed plugins:
*:

Some plugins failed to download!
Download integrity: github-oauth
Download integrity: workflow-aggregator
ERROR: Service 'jenkins' failed to build: The command '/bin/sh -c /usr/local/bin/install-plugins.sh github-oauth workflow-aggregator' returned a non-zero code: 1
```

**Comment by carlossg** [comment]
You are not saying *what* are you building

**Comment by jmMeessen** [comment]
indeed (too obvious for me). Sorry.

This is the dockerfile:
```
[root@ns360684 docker]# cat jenkins-dockerfile/Dockerfile
#FROM jenkins:latest
FROM jenkinsci/jenkins:latest

RUN /usr/local/bin/install-plugins.sh github-oauth workflow-aggregator

#RUN /usr/local/bin/install-plugins.sh \
#github-api:1.76 \
#structs:1.3 \
#workflow-step-api:2.3 \
#workflow-scm-step:2.2 \
#credentials:2.1.4 \
#junit:1.18 \
#script-security:1.21 \
#matrix-project:1.7.1 \
#windows-slaves:1.1 \
#ssh-credentials:1.12 \
#icon-shim:2.0.3 \
#matrix-auth:1.4 \
#antisamy-markup-formatter:1.5 \
#git-client:1.19.7 \
#scm-api:1.2 \
#mailer:1.17 \
#git:2.5.3 \
#github-oauth:0.24

COPY enableGitHubOAuth.groovy /usr/share/jenkins/ref/init.groovy.d/enableGitHubOAuth.groovy.override
COPY load-slavery-key.groovy /usr/share/jenkins/ref/init.groovy.d/load-slavery-key.groovy.override
```

Here the abstract of the docker-compose file:
````
  jenkins:
    build: ./jenkins-dockerfile
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - JENKINS_SLAVE_AGENT_PORT=50000
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins2-data:/var/jenkins_home
      - /data/ci/ssh-keys:/ssh-keys
    env_file:
      - /data/ci/GitHub_OAuth_IDs.env
    restart: unless-stopped
````
