### ISSUE TITLE
Error creating: pods "" is forbidden: SecurityContext.FSGroup is forbidden

### ISSUE THREAD

**Issue by hiscal2015** [jenkinsci/docker#486]
I'm trying to deploy Jenkins in Kubernetes but failed:

Kubernetes version: 1.5.4
Jenkins Docker version: 2.46.2

Part of my Kubernetes deployment yaml:
```
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jenkins
    spec:
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
      containers:
      - name: jenkins
        image: jenkinsci/jenkins:2.46.2
        ports:
          - containerPort: 8080
          - containerPort: 50000
```

I got below error:
```
Error creating: pods "" is forbidden: SecurityContext.FSGroup is forbidden
```

I can't find out what's the problem here, please help, thanks.
