### ISSUE TITLE
Groovy hook scripts not found

### ISSUE THREAD

**Issue by mlabouardy** [jenkinsci/docker#627]
I extended the image with some customs groovy scripts to setup credentials, but I couldn't found the scripts inside the container in runtime

```
FROM jenkins/jenkins:2.89.2
MAINTAINER mlabouardy <mohamed@labouardy.com>

COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

COPY security.groovy /usr/share/jenkins/ref/init.groovy.d/security.groovy
COPY setup-credentials.groovy /usr/share/jenkins/ref/init.groovy.d/setup-credentials.groovy
```

### Docker commands that you execute

I'm using the following compose to deploy the service:

```
version: "3.3"

services:
  jenkins:
    image: mlabouardy/jenkins
    ports:
      - 8080:8080
    secrets:
      - jenkins-username
      - jenkins-password
      - registry-username
      - registry-password
      - ssh-username
    configs:
      - source: private_key
        target: /var/jenkins_home/.ssh/id_rsa
        mode: 0600
        uid: '1000'
        gid: '1000'
      - source: public_key
        target: /var/jenkins_home/.ssh/id_rsa.pub
        mode: 0600
        uid: '1000'
        gid: '1000'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      placement:
        constraints:
          - node.role == manager

configs:
  private_key:
    file: /home/mlabouardy/.ssh/id_rsa
  public_key:
    file: /home/mlabouardy/.ssh/id_rsa.pub

secrets:
  jenkins-username:
    external: true
  jenkins-password:
    external: true
  registry-username:
    external: true
  registry-password:
    external: true
  ssh-username:
    external: true
```

### Actual result

Scripts are not copied over.

### Expected outcome

Execute hook scripts

### Output of `docker version`

```
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.4
 Git commit:   3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
 Built:        Mon Jan  8 22:44:09 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.4
 Git commit:   402dd4a/17.09.1-ce
 Built:        Mon Jan  8 22:44:42 2018
 OS/Arch:      linux/amd64
 Experimental: false
```

### Other relevant information

Environment: Amazon EC2
