### ISSUE TITLE
[Docs] Add info about docker usage inside container

### ISSUE THREAD

**Issue by arteniioleg** [jenkinsci/docker#640]
I install `docker` inside jenkins container to be able to run this `Jenkinsfile`

```
pipeline {
    agent { docker 'node:6.3' }
    stages {
        stage('build') {
            steps {
                sh 'npm --version'
            }
        }
    }
}
```

This is how I install and run docker inside container:

1. `Dockerfile`

```
FROM jenkins/jenkins:lts

USER root
RUN apt-get update \
    && apt-get install -y \
        nano wget unzip tar curl apt-transport-https ca-certificates gnupg2 software-properties-common \
    && (curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | apt-key add -) \
    && add-apt-repository \
        "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
        $(lsb_release -cs) \
        stable" \
    && apt-get update \
    && apt-get install -y docker-ce

USER jenkins
```

2. `docker-compose.yml`

```
version: '3.4'
services:
    jenkins_test:
        container_name: jenkins_test
        build: .
        privileged: true
        volumes:
            - "./.volumes/jenkins_home:/var/jenkins_home"
            - "./.volumes/docker_data:/var/lib/docker"
        ports:
            - "7008:8080"
            - "7005:50000"
```

3. Then I start docker manually

```
docker exec -it -u 0 jenkins_test dockerd --group jenkins
```

-----

### Questions

1. How to made docker start automatically inside container? (`dockerd` must be executed as `root`)
2. Is this a good practice? Why there is no info about this in docs?
3. [These docs](https://jenkins.io/doc/tutorials/build-a-node-js-and-react-app-with-npm/#run-jenkins-in-docker) advice `-v /var/run/docker.sock:/var/run/docker.sock` but I don't want Jenkins to pollute my local docker instance, that's why I run docker inside Jenkins container. Which solution is recommended?
