### ISSUE TITLE
unable to login after update

### ISSUE THREAD

**Issue by MichalTaratuta** [jenkinsci/docker#811]
# Issues and Contributing

Please note that only issues related to this Docker image will be addressed here.

* If you have Docker related issues, please ask in the [Docker user mailing list](https://groups.google.com/forum/#!forum/docker-user).
* If you have Jenkins related issues, please ask in the [Jenkins mailing lists](https://jenkins-ci.org/content/mailing-lists).
* If you are not sure, then this is probably not the place to create an issue and you should use any of the previously mentioned mailing lists.

If after going through the previous checklist you still think you should create an issue here please provide:

### Docker commands that you execute
```yaml
services:
  jenkins:
    #image: jenkins/jenkins:2.149
    image: jenkins/jenkins:2.168 
    environment:
      - "jenkins_home:/var/jenkins_home"
    labels:
      - traefik.backend=jenkins
      - traefik.frontend.rule=Host:jenkins.oc.lab
      - traefik.docker.network=pipeline
      - traefik.enable=true
      - traefik.port=8080
    ports:
      - "8888:8080"
    volumes:
        - jenkins_home:/var/jenkins_home
    restart: always
```
### Actual result
Unable to login to the instance after the update, switching back to `jenkins/jenkins:2.149`, resolves the issue
### Expected outcome
Login working with existing users
### Output of `docker version`
Docker version 18.09.3, build 774a1f4
