### ISSUE TITLE
Plugins not installed by install-plugins.sh

### ISSUE THREAD

**Issue by mietzen** [jenkinsci/docker#903]
# Issues and Contributing

I'm not able to install Plugins with the provided information from the README.md

### Docker commands that you execute

Command:
`docker-compose up -d --build`

Dockerfile:
```
FROM jenkins/jenkins:lts
COPY certs /tmp/certs
COPY SquishPlugin.hpi $JENKINS_HOME/plugins/SquishPlugin.hpi
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
RUN echo 2.0 > /usr/share/jenkins/ref/jenkins.install.UpgradeWizard.state

USER root
WORKDIR /tmp/certs
RUN bash /tmp/certs/set_git_certs_linux.sh

USER jenkins
WORKDIR /
RUN git config --global http.sslKey    /usr/local/share/ca-certificates/some.key \
 && git config --global http.sslCert   /usr/local/share/ca-certificates/some.crt
```
docker-compose.yml
```
version: "3.7"

services:
    jenkins:
        build:
          context: .
        image: my/jenkins:lts
        container_name: jenkins
        restart: always
        ports:
          - 8080:8080
          - 50000:50000
        volumes:
          - home:/var/jenkins_home

volumes:
  home:
```

### Actual result

I'm ask to install plugins and the plugins don't appear in the Web UI

### Expected outcome

I'm not ask to install plugins and the plugins appear in the Web UI

### Have you tried a non-dockerized Jenkins and get the expected outcome?

No

### Output of `docker version`

```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:54:09 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:52:40 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
### Other relevant information

Building of the image finishes without errors. All Plugins are in the `REF` folder, even the SquishPlugin.hpi is located in `$JENKINS_HOME/plugins` after build, but it doesn't show up as installed plugin. Restarting the container has no effect.
