### ISSUE TITLE
ARM image is Unstable and Crashes Periodically

### ISSUE THREAD

**Issue by jroose** [jenkinsci/docker#941]
### Docker commands that you execute
Following Kubernetes YAML was used to run the image:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master
  labels:
    app: jenkins-master
    tier: devops
spec:
  selector:
    matchLabels:
      app: jenkins-master
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      hostname: jenkins-master
      nodeName: c4a-1
      volumes:
      - name: jenkins-home
        hostPath:
          path: /media/hdd/jenkins_home
      containers:
      - name: jenkins-master
        tty: true
        stdin: true
        image: jenkins4eval/jenkins:2.225-alpine-arm64
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: web
        - containerPort: 5000
          name: slave-port   
        volumeMounts:
        - name: jenkins-home 
          mountPath: /var/jenkins_home
      imagePullSecrets:
      - name: regcred
```

### Actual result
Jenkins crashes and docker image restarts ~every 10 minutes with the following error message. 
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (assembler_aarch64.hpp:1156), pid=6, tid=0x0000ffff900bdaa0
#  guarantee(Rs != Rn && Rs != Rt) failed: unpredictable instruction
#
# JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-aarch64 compressed oops)
# Derivative: IcedTea 3.12.0
# Distribution: Custom build (Sat May  4 17:44:26 UTC 2019)
# Core dump written. Default location: //core or core.6
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid6.log
#
# Compiler replay data is saved as:
# /tmp/replay_pid6.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   https://icedtea.classpath.org/bugzilla
#
```
### Expected outcome
A stable Jenkins

### Have you tried a non-dockerized Jenkins and get the expected outcome?
Not recently

### Output of `docker version`
```
alaric@c4a-1:~/pods/jenkins$ docker version
Client:
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.9
 Git commit:        6a30dfca03
 Built:             Mon Sep 16 03:58:25 2019
 OS/Arch:           linux/arm64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.9
  Git commit:       6a30dfca03
  Built:            Wed Sep 11 22:45:55 2019
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.2.10-0ubuntu1
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
```

### Other relevant information
Running on a Raspberry PI 4 with 4GB of RAM
No Jenkins agents were running
Image utilized: jenkins4eval/jenkins:2.225-alpine-arm64

Docker container restarted 8 times in 81 minutes. After 87 minutes it has still only restarted 8 times.  Seems to take 10-15 minutes on average to crash.
```
alaric@c4a-1:~/pods/jenkins$ kubectl get pods -o wide
NAME                            READY   STATUS    RESTARTS   AGE   IP            NODE    NOMINATED NODE   READINESS GATES
jenkins-master-68df6766-zgtbq   1/1     Running   8          87m   10.244.0.13   c4a-1   <none>           <none>
```
Same behavior was observed in: jenkins4eval/jenkins:2.209-alpine-arm64
